import React from 'react';
import { 
  Leaf, 
  TreePine, 
  Sparkles, 
  TrendingDown, 
  CheckCircle2, 
  Train, 
  Utensils, 
  Droplet, 
  ShoppingBag,
  Award
} from 'lucide-react';
import { TripPlan } from '../../types';

interface SustainabilityDashboardProps {
  trip: TripPlan;
}

export const SustainabilityDashboard: React.FC<SustainabilityDashboardProps> = ({ trip }) => {
  const score = trip.sustainabilityScore || 92;
  const carbonKg = trip.carbonKg || 36.2;
  const carbonSavedKg = trip.carbonSavedKg || 28.5;

  return (
    <div className="max-w-6xl mx-auto space-y-8">
      
      {/* Top Banner */}
      <div className="bg-gradient-to-r from-emerald-800 via-teal-800 to-ocean-900 rounded-3xl p-8 sm:p-10 text-white relative overflow-hidden shadow-xl">
        <div className="relative z-10 max-w-2xl space-y-3">
          <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-white/10 backdrop-blur-md text-emerald-300 text-xs font-bold border border-white/10">
            <Leaf className="w-3.5 h-3.5" />
            <span>SIH Green Tourism Initiative</span>
          </div>
          <h1 className="text-3xl sm:text-4xl font-extrabold tracking-tight">
            Travel Better. Protect Our Planet.
          </h1>
          <p className="text-sm sm:text-base text-emerald-100">
            Every itinerary generated by TravelAI measures estimated carbon expenditure, promotes low-emission rail corridors, and routes economic benefits directly to local indigenous artisans.
          </p>
        </div>
      </div>

      {/* Main Score & Carbon Comparison Cards */}
      <div className="grid grid-cols-1 lg:grid-cols-3 gap-6">
        
        {/* Score Card */}
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-emerald-100 shadow-soft flex flex-col justify-between">
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-500">Trip Eco Rating</span>
              <Award className="w-5 h-5 text-emerald-600" />
            </div>

            <div className="flex items-baseline gap-2">
              <span className="text-5xl font-black text-emerald-700">{score}</span>
              <span className="text-lg font-bold text-slate-400">/ 100</span>
            </div>

            <p className="text-xs font-semibold text-emerald-900">
              "Your Trip Sustainability Score: {score}/100"
            </p>
            <p className="text-xs text-slate-500 leading-relaxed">
              Rated in the top 5% of eco-friendly itineraries across Indian tourism routes.
            </p>
          </div>

          <div className="w-full bg-slate-100 h-2.5 rounded-full overflow-hidden mt-6">
            <div
              className="bg-emerald-500 h-full rounded-full transition-all duration-500"
              style={{ width: `${score}%` }}
            />
          </div>
        </div>

        {/* Carbon Footprint Card */}
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200/80 shadow-soft flex flex-col justify-between">
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-500">Carbon Footprint</span>
              <TrendingDown className="w-5 h-5 text-ocean-600" />
            </div>

            <div className="text-4xl sm:text-5xl font-black text-slate-900">
              {carbonKg} <span className="text-lg font-bold text-slate-400">kg CO₂</span>
            </div>

            <p className="text-xs font-semibold text-ocean-700">
              Total greenhouse impact for {trip.request.travelers} travelers
            </p>
            <p className="text-xs text-slate-500 leading-relaxed">
              Taking scenic trains and local group transit saved approx <strong>{carbonSavedKg} kg CO₂</strong> vs solo flights or diesel SUVs.
            </p>
          </div>

          <div className="p-2.5 rounded-xl bg-ocean-50 text-ocean-900 text-[11px] font-bold mt-4 flex items-center gap-1.5">
            <TreePine className="w-4 h-4 text-ocean-600" />
            <span>Equivalent to planting 2 native mountain trees</span>
          </div>
        </div>

        {/* Local Economic Contribution */}
        <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200/80 shadow-soft flex flex-col justify-between">
          <div className="space-y-3">
            <div className="flex items-center justify-between">
              <span className="text-xs font-bold uppercase tracking-wider text-slate-500">Local Economy Retention</span>
              <ShoppingBag className="w-5 h-5 text-sunset-500" />
            </div>

            <div className="text-4xl sm:text-5xl font-black text-sunset-600">
              86%
            </div>

            <p className="text-xs font-semibold text-slate-700">
              Direct Community Benefit
            </p>
            <p className="text-xs text-slate-500 leading-relaxed">
              By prioritizing tribal cooperative coffee, local homestays, and handicraft artisans, your trip expenditure stays directly in local hands.
            </p>
          </div>

          <div className="p-2.5 rounded-xl bg-amber-50 text-amber-900 text-[11px] font-bold mt-4 flex items-center gap-1.5">
            <Sparkles className="w-4 h-4 text-amber-600" />
            <span>Certified Fair Tourism Partner</span>
          </div>
        </div>

      </div>

      {/* Sustainable Suggestions & Responsible Guidelines (Requirement #14) */}
      <div className="bg-white rounded-3xl p-6 sm:p-8 border border-slate-200/80 shadow-soft space-y-6">
        <h3 className="text-lg font-bold text-slate-900">
          AI Recommendations for a Greener Journey
        </h3>

        <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
          
          <div className="p-5 rounded-2xl bg-emerald-50/70 border border-emerald-200/80 space-y-2">
            <div className="w-9 h-9 rounded-xl bg-emerald-600 text-white flex items-center justify-center font-bold">
              <Train className="w-5 h-5" />
            </div>
            <h4 className="text-sm font-bold text-slate-800">Choose train instead of flight</h4>
            <p className="text-xs text-slate-600 leading-relaxed">
              Opting for the Vistadome train cuts carbon emissions by 68% and eliminates runway airport transfers.
            </p>
          </div>

          <div className="p-5 rounded-2xl bg-ocean-50/70 border border-ocean-200/80 space-y-2">
            <div className="w-9 h-9 rounded-xl bg-ocean-600 text-white flex items-center justify-center font-bold">
              <Utensils className="w-5 h-5" />
            </div>
            <h4 className="text-sm font-bold text-slate-800">Support local restaurants</h4>
            <p className="text-xs text-slate-600 leading-relaxed">
              Dine at village stalls serving bamboo chicken and locally harvested grains to minimize supply-chain food miles.
            </p>
          </div>

          <div className="p-5 rounded-2xl bg-amber-50/70 border border-amber-200/80 space-y-2">
            <div className="w-9 h-9 rounded-xl bg-amber-600 text-white flex items-center justify-center font-bold">
              <Droplet className="w-5 h-5" />
            </div>
            <h4 className="text-sm font-bold text-slate-800">Avoid single-use plastic</h4>
            <p className="text-xs text-slate-600 leading-relaxed">
              Carry the included reusable stainless steel water bottle. Refill at certified RO drinking stations at your homestay.
            </p>
          </div>

        </div>
      </div>

    </div>
  );
};
