import { CommunityPost } from '../types';

export const COMMUNITY_POSTS: CommunityPost[] = [
  {
    id: 'post-1',
    author: {
      name: 'Priya Sharma',
      avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=200&q=80',
      badge: 'Certified Eco Explorer',
      location: 'Bengaluru, India'
    },
    destination: 'Araku Valley',
    title: 'The early morning Vistadome train through Ananthagiri mist is unforgettable!',
    content: 'Took the 7:00 AM Vistadome coach from Vizag to Araku yesterday following TravelAIs advice. Looking straight through the glass ceiling at waterfalls cascading beside the train track was mesmerizing. Also, do not miss the bamboo chicken at Chaparai village!',
    image: 'https://images.unsplash.com/photo-1596895111956-bf1cf0599ce5?auto=format&fit=crop&w=1000&q=80',
    rating: 5,
    likes: 124,
    isLiked: false,
    commentsCount: 18,
    date: '2 hours ago',
    tags: ['#ArakuValley', '#Vistadome', '#EcoTravel', '#TribalFood']
  },
  {
    id: 'post-2',
    author: {
      name: 'Rohan Deshmukh',
      avatar: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=200&q=80',
      badge: 'Backpacking Pro',
      location: 'Pune, India'
    },
    destination: 'Goa',
    title: 'Hidden beach discovered: Kakolem (Tiger Beach) is a must for peace lovers',
    content: 'Most tourists head straight to Baga or Calangute, but the TravelAI Hidden Gem feature guided us south to Kakolem. Tiny natural freshwater stream dropping directly into the ocean. Zero crowd, just clean sand and turquoise water!',
    image: 'https://images.unsplash.com/photo-1512343879784-a960bf40e7f2?auto=format&fit=crop&w=1000&q=80',
    rating: 4.8,
    likes: 89,
    isLiked: true,
    commentsCount: 12,
    date: 'Yesterday',
    tags: ['#GoaDiaries', '#SecretBeaches', '#SunsetMagic']
  },
  {
    id: 'post-3',
    author: {
      name: 'Ananya & Karthik',
      avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&w=200&q=80',
      badge: 'Honeymoon Duo',
      location: 'Hyderabad, India'
    },
    destination: 'Kerala (Munnar)',
    title: 'Waking up in a spice valley eco-cottage with floating cloud layers',
    content: 'We followed the romantic nature itinerary generated by TravelAI. The Kolukkumalai tea sunrise tour was freezing cold at 5 AM but watching the orange sun break through clouds above 7,000 feet made every second worth it.',
    image: 'https://images.unsplash.com/photo-1602216056096-3b40cc0c9944?auto=format&fit=crop&w=1000&q=80',
    rating: 5,
    likes: 245,
    isLiked: false,
    commentsCount: 31,
    date: '3 days ago',
    tags: ['#KeralaGodsOwnCountry', '#MunnarTea', '#HoneymoonVibes']
  }
];
